DX menus, items and positions
IllusionMods/HS2-Translation pull request #37
Opened 2020-10-30 21:33 UTC by SpockBauru

Also shortened some old positions to fit in the screen

2020-10-30 21:47 UTC, GeBo1 requested changes
Looks good. Flagged a few things to fix.

2020-10-30 21:47 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/list/characustom/50/fo_top_50/translation.txt
> +触手（上）=Tentacles (top)
`top` -> `Top`

2020-10-30 21:47 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/list/characustom/50/fo_gloves_50/translation.txt
> +触手（腕）=Tentacles (arms)
`arms`->`Arms`

2020-10-30 21:47 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/list/characustom/50/so_hair_b_50/translation.txt
> +ボリュームぱっつんポニー=Volumous Long Ponytail
Voluminous?

2020-10-30 21:47 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/list/h/animationinfo/50/3p_50/translation.txt
> +W手コキ舐め入れ替え=W Hand. Lick. Swap
Maybe use `HJ` rather than `Hand.`?

2020-10-30 21:47 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/map/list/mapinfo/50/00/translation.txt
>  触手部屋=Tentacle room
`room` -> `Room`

2020-10-30 21:47 UTC, GeBo1 commented on Translation/en/Text/Main/GameMenus.txt
> +■特別待遇室へ行く=■ Go to the VIP Lobby
Things like this should be an SR regex in Formatting:
```
sr:^■(.*)$=■ $1
```

2020-10-30 21:47 UTC, GeBo1 commented on Translation/en/Text/Main/GameMenus.txt
> +～夜のお散歩プラン～=~Night Walk Service~
Also `sr` in Formatting:
```
sr:^～(.*)～$=~$1~
```

2020-10-30 21:52 UTC, GeBo1 commented on Translation/en/Text/Main/Options.txt
> +タイトル２=Title 2
BGM titles live in the assets, do we need them here as well for some reason?

- `Translation/en/RedirectedResources/assets/abdata/gamedata/bgmname/50/bgmname/translation.txt`
- `Translation/en/RedirectedResources/assets/abdata/studio/info/50/bgm_50/translation.txt`

2020-10-30 22:01 UTC, SpockBauru commented on Translation/en/Text/Main/GameMenus.txt
> +■特別待遇室へ行く=■ Go to the VIP Lobby
Something is wrong with this text, if I put just one version of "Go to the VIP Lobby" sometimes it randomly don't translate, While putting both versions it always translate.

2020-10-30 22:02 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/map/list/mapinfo/50/00/translation.txt
>  触手部屋=Tentacle room
Fixed.

2020-10-30 22:02 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/list/h/animationinfo/50/3p_50/translation.txt
> +W手コキ舐め入れ替え=W Hand. Lick. Swap
Agreed.

2020-10-30 22:02 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/list/characustom/50/so_hair_b_50/translation.txt
> +ボリュームぱっつんポニー=Volumous Long Ponytail
Fixed.

2020-10-30 22:02 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/list/characustom/50/fo_gloves_50/translation.txt
> +触手（腕）=Tentacles (arms)
Fixed.

2020-10-30 22:02 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/list/characustom/50/fo_top_50/translation.txt
> +触手（上）=Tentacles (top)
Fixed.

2020-10-30 22:16 UTC, SpockBauru commented on Translation/en/Text/Main/GameMenus.txt
> +～夜のお散歩プラン～=~Night Walk Service~
Tried to scope to level 15, seems to work :)

2020-10-30 22:26 UTC, SpockBauru commented on Translation/en/Text/Main/Options.txt
> +タイトル２=Title 2
Woops, fixed!

2020-10-30 22:41 UTC, GeBo1 approved these changes

2020-10-30 22:41 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/list/h/animationinfo/50/3p_50/translation.txt
> +W手コキ舐め入れ替え=W HJ. Lick. Swap
Drop the `.`

2020-10-31 01:13 UTC, GeBo1 commented on Translation/en/Text/Main/GameMenus.txt
> +■特別待遇室へ行く=■ Go to the VIP Lobby
We'll figure it out later then, let's commit it for now.

2020-10-31 01:14 UTC, merged