translation from c00/30/16 to 20
IllusionMods/HS2-Translation pull request #66
Opened 2021-06-15 22:36 UTC by GenericUser394753

several commits

2021-06-15 23:49 UTC, SpockBauru requested changes

2021-06-15 23:49 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/15/2/translation.txt
> +女が好きな方の元へ訪れたのですから、セックスをするのは自明のことですね。=Since you're known for liking women, it's obvious that I came to have sex.
```suggestion
女が好きな方の元へ訪れたのですから、セックスをするのは自明のことですね。=Since you're known to like women, it's obvious that I came to have sex. 
```

2021-06-15 23:49 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/15/1/translation.txt
> +突然お邪魔してすみません。少しだけ私とお付き合いいただけないでしょうか？=I'm sorry to bother you so suddenly. I was wondering if you could keep me company for a little while?
```suggestion
突然お邪魔してすみません。少しだけ私とお付き合いいただけないでしょうか？=I'm sorry to bother you so suddenly. I was wondering if you could keep me company for a little while.
```
or maybe
``````suggestion
突然お邪魔してすみません。少しだけ私とお付き合いいただけないでしょうか？=I'm sorry to bother you so suddenly. I was wondering, would you keep me company for a little while?
```

2021-06-15 23:49 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/15/1/translation.txt
> +無意識のうちに、お部屋の近くまで足を運んでおりました。今日も少しだけお付き合いいただけると嬉しいです。=I wandered by without realising. I would be happy if you could stay with me for a little today.
The first part is strange, the girl should mention your room

2021-06-15 23:49 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/1/translation.txt
> +[H]がいなくなった・・・=[H] has disappeared...
I think this is when the girl leaves the hotel forever. She didn't disappeared, you know that she's gone.

2021-06-15 23:49 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +一つご報告します、我慢の限界がきて失禁してしまいそうです。失禁プレイがお嫌いでなければ、このままでも構いませんが……？=I would like to report that I've reached the limit of my patience and incontience. But if this is the sort of play you like, I guess you co
```suggestion
一つご報告します、我慢の限界がきて失禁してしまいそうです。失禁プレイがお嫌いでなければ、このままでも構いませんが……？=I would like to report that I've reached the limit of my patience and incontience. But if this is the sort of play you like, I guess you could keep me like this.
```

2021-06-15 23:49 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/4/translation.txt
> +この様な間抜けな女は、失望されて当然ですね……=A woman as dumb as myself deserves to be dissapointed...
```suggestion
この様な間抜けな女は、失望されて当然ですね……=A woman as dumb as me deserves to be disappointed...
```

2021-06-16 00:03 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/15/1/translation.txt
> +無意識のうちに、お部屋の近くまで足を運んでおりました。今日も少しだけお付き合いいただけると嬉しいです。=I wandered by without realising. I would be happy if you could stay with me for a little today.
right, i was wondering if i should say wandered by your room, but for some reason i decided thought it sounded a bit too forced (since technically she is already there, there's no need to specify where she is :P) . i can put it back, i don't think it makes too much of a difference

2021-06-16 00:08 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/1/translation.txt
> +[H]がいなくなった・・・=[H] has disappeared...
if that's the scene, yeah, it fits better. it's again something i corrected since i thought she was just hiding, the rest of the files are different lines about her being caught :P

2021-06-16 00:23 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/15/1/translation.txt
> +突然お邪魔してすみません。少しだけ私とお付き合いいただけないでしょうか？=I'm sorry to bother you so suddenly. I was wondering if you could keep me company for a little while?
yeah, i guess i was going for a bit of a mix between an indirect question and yet keeping the interrogative tonality, which isn't really correct. i'll try to avoid if from now on, it's one of the things i tend to do quite a bit.

2021-06-16 00:29 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +一つご報告します、我慢の限界がきて失禁してしまいそうです。失禁プレイがお嫌いでなければ、このままでも構いませんが……？=I would like to report that I've reached the limit of my patience and incontience. But if this is the sort of play you like, I guess you co
here i'd keep the ? (actually, i think ...? would fit even better, especially since it's in the jp line too), since it's just her being hesitant/uncertain.

2021-06-16 10:05 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/15/1/translation.txt
> +ふと、あなたにお会いしたくなりまして……押しかけてしまい申し訳ございません。=I had a sudden urge to meet you... I'm sorry to impose on you.
`on you` is probably redundant in Engish

```suggestion
ふと、あなたにお会いしたくなりまして……押しかけてしまい申し訳ございません。=I had a sudden urge to meet you... I'm sorry to impose.
```

2021-06-16 10:09 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/15/2/translation.txt
> +ありがとうございました。これ以上お傍にいたら、益々離れがたくなるので、これで失礼致します。=Thank you so much! If I stay with you any longer, it will be much more dificult to part, so I will take my leave now.
Simpler?
```suggestion
ありがとうございました。これ以上お傍にいたら、益々離れがたくなるので、これで失礼致します。=Thank you so much! If I stay with you any longer, it will be hard to leave, so I'll go now.
```

Or less literal?
```suggestion
ありがとうございました。これ以上お傍にいたら、益々離れがたくなるので、これで失礼致します。=Thank you so much! The longer I stay with you, the harder it is to leave, so I'd better go now.
```

2021-06-16 10:13 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/15/4/translation.txt
> +もしかして、お疲れで早く休まれたかったのでしょうか？　配慮が足りず申し訳ございません。=Could it be that you were tired and wanted to go to bed early? I appologise for being inconsiderate.
```suggestion
もしかして、お疲れで早く休まれたかったのでしょうか？　配慮が足りず申し訳ございません。=Maybe you were tired and wanted to go to bed early? Sorry for being so inconsiderate.
```

2021-06-16 10:18 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/1/translation.txt
> +帰られてしまいましたね、残念な事です。=I'm sorry to see that you have returned.
What's the exact context here? Who is `I` and `you` in this line?   
Is it Fur talking to the player?
`I'm sorry to report that they've left.`
The player talking to Fur?
`I'm sorry to hear that they've gone.`

I'm pretty sure it's no is sorry someone is back, so `returned` seems off.

2021-06-16 10:21 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/1/translation.txt
> +[H]がいなくなった・・・=[H] is gone...
Is this where the player expects to meet `[H]` but they've left due to being angry (then they talk to Fur who says they've left and then you can decide to search, or teach them a lesson, or let them go)?

If so I'd suggest `[H]'s not here...`

2021-06-16 10:26 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/5/translation.txt
> +ただただ不愉快です。これ以上、私に関わらないでもらえますか？=I find it simply unpleasant. Could you please not engage me any further?
This reads a bit awkwardly

```suggestion
ただただ不愉快です。これ以上、私に関わらないでもらえますか？=That was unpleasant. Could you please leave me alone from now on?
```

2021-06-16 10:27 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/5/translation.txt
>  //帰られてしまいましたね、残念な事です。=
You commented out the MTL but didn't translate this line

2021-06-16 10:31 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/15/2/translation.txt
> +ありがとうございました。これ以上お傍にいたら、益々離れがたくなるので、これで失礼致します。=Thank you so much! If I stay with you any longer, it will be much more dificult to part, so I will take my leave now.
i like the 2nd one more, so i went with it. considered using a but in front, decided against it.

2021-06-16 10:32 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/0/translation.txt
> +私としたことが、不覚です……=I made a blunder...
No one would say this non-ironicly.  `I made a mistake...`, `I screwed up...`, `I blew it...`, `My bad...` (depending on tone you want).

2021-06-16 10:40 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +一番見られたくない方に、見つかるとは……みっともない姿をお見せして申し訳ございません。=I'm deeply sorry to appear as such... In front of the person I least wanted to see me like this.
```suggestion
一番見られたくない方に、見つかるとは……みっともない姿をお見せして申し訳ございません。=Discovered by the last person I'd want to find me... I'm ashamed you found me in this state.
```

2021-06-16 10:44 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +……間抜けな姿になっていることは充分自覚しておりますので、あまり見ないでいただけると助かります。=...I'm fully aware of how stupid I look, so I would appreciate it if you didn't stare too much.
This is ok, but trying to sound more natural
```suggestion
……間抜けな姿になっていることは充分自覚しておりますので、あまり見ないでいただけると助かります。=I know I look... stupid.  Please don't stare.
```

2021-06-16 10:47 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/1/translation.txt
> +帰られてしまいましたね、残念な事です。=I'm sorry to see that you have returned.
it seems fur is talking to the player. i never got to that scene in the game, so i don't really know how it plays out, in my mind, fur saw the player returning just after he left, so she probably imagined something was wrong. I guess I was reading too much into how the detailed the situation was. fur reporting the girl is gone makes way more sense indeed, i'll continue under that assumption

2021-06-16 10:48 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/1/translation.txt
> +帰られてしまいましたね、残念な事です。=I'm sorry to see that you have returned.
the term that fur uses is indeed return, but she is probably talking about the girl returning home or something

2021-06-16 10:55 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +ここへきて尿意が……私はとうとう天から見放されたようです……=I can feel the urge to pee... It looks like my time has run out...
I think the first part is more either
- "It's happening right now": `I'm peeing myself...`
- "It's going to happen in a second": `I'm going to wet myself...`

While the MTL for the second part sounds silly, it's probably closer. Maybe: `The gods have forsaken me...` or `My luck has run out...`

2021-06-16 11:04 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +……すみません。理由を明かすことはできませんが、一刻も早く助けていただけないでしょうか。お願い致します。=...Excuse me. I can't reveal the reason, but could you please help me as soon as possible? Thank you.
```suggestion
……すみません。理由を明かすことはできませんが、一刻も早く助けていただけないでしょうか。お願い致します。=...Excuse me. I can't explain, but could you please help me as soon as possible? Thank you.
```
or

```suggestion
……すみません。理由を明かすことはできませんが、一刻も早く助けていただけないでしょうか。お願い致します。=...Excuse me. Quickly, I can't explain, but could you please help me? Thank you.
```

2021-06-16 11:09 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +犯しまくる絶好の機会だ、そういったことをお考えなのでしょうね。=I guess you're probably thinking this is a great opportunity to attack me, right?
```suggestion
犯しまくる絶好の機会だ、そういったことをお考えなのでしょうね。=You're probably thinking this is the perfect opportunity to have your way with me, right?
```

Could probably loose the `, right?`, but whatever you think.

2021-06-16 11:09 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/5/translation.txt
> +ただただ不愉快です。これ以上、私に関わらないでもらえますか？=I find it simply unpleasant. Could you please not engage me any further?
i think it's when the girl is caught but leaves? (maybe it's a talking option, again, i have no idea how this scene plays out). i was thinking she was referring to the whole situation, and thus deciding to go. (fur also has a line where she again says that [h] has left). Maybe "It was unpleasant. Could you please leave me alone from now on?" fits better in this case? or do i keep it as "that"?

2021-06-16 11:11 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/5/translation.txt
>  //帰られてしまいましたね、残念な事です。=
yeah, i already changed that above, it will be propagated by the dupe tool later after approval

2021-06-16 11:11 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/0/translation.txt
> +私としたことが、不覚です……=I made a blunder...
fair enough :D

2021-06-16 11:13 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +一つご報告します、我慢の限界がきて失禁してしまいそうです。失禁プレイがお嫌いでなければ、このままでも構いませんが……？=I would like to report that I've reached the limit of my patience and incontience. But if this is the sort of play you like, I guess you co
```suggestion
一つご報告します、我慢の限界がきて失禁してしまいそうです。失禁プレイがお嫌いでなければ、このままでも構いませんが……？=Just so you know, I'm about to lose control of my bladder...  But if that doesn't bother you, should we keep going...?
```

2021-06-16 11:15 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/2/translation.txt
> +本当はまだまだお礼の言葉を述べたいのですが……すみません、失礼します。=I would really like to thank you some more, but... I'm sorry, I need to go.
```suggestion
本当はまだまだお礼の言葉を述べたいのですが……すみません、失礼します。=I would really like to thank you some more, but...  I need to go, sorry.
```

2021-06-16 11:18 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/2/translation.txt
> +お手数をおかけしました。同じ失態をしないように心に留めておきます。=I appologise for the inconvenience. I'll try not to make the same blunder again.
`blunder` -> `mistake`

2021-06-16 11:20 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +一番見られたくない方に、見つかるとは……みっともない姿をお見せして申し訳ございません。=I'm deeply sorry to appear as such... In front of the person I least wanted to see me like this.
my non-english brain kind of gets the idea that she has something against the guy if there's no other information. (girl is at neutral affection from the rule of thumb. 
how would you feel about: "Discovered by the last person I wanted to see me like this... I'm ashamed you found me in this state."
or "Discovered by the last person I'd want to see me like this... I'm ashamed you found me in this state." if you want to keep the would there

2021-06-16 11:22 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/2/translation.txt
> +お陰で大事に至らずに済みました。改めてお礼申し上げます。=Thanks to you, it didn't become a serious problem. Thank you once again.
Trying to be less redundant with the thanks, but also keep that she feels indebted
```suggestion
お陰で大事に至らずに済みました。改めてお礼申し上げます。=Thanks to you, it didn't become a serious problem. I owe you one, again.
```

```suggestion
お陰で大事に至らずに済みました。改めてお礼申し上げます。=Because of you, it didn't become a serious problem. Thank you, again.
```

2021-06-16 11:24 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/2/translation.txt
> +優しい一面もあるのですね。少しだけ見直しました。=So there's a gentle side to you, isn't there? I've changed my opinion a little.
More natural sounding?
```suggestion
優しい一面もあるのですね。少しだけ見直しました。=So there's a gentle side to you, isn't there? Maybe I was wrong about you.
```

2021-06-16 11:25 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +……間抜けな姿になっていることは充分自覚しておりますので、あまり見ないでいただけると助かります。=...I'm fully aware of how stupid I look, so I would appreciate it if you didn't stare too much.
small letter after "..." ? until now i used upper case every time after it, even if it's the same sentence. i could just avoid it with "i know i look stupid.... [...]. i'll defer to your opinion, but i am curious if i should keep using upper case after "..." or if i can go with lower case too.

2021-06-16 11:26 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/2/translation.txt
> +……襲わないのですか？　いえ、がっかりしてませんよ。=...You're not going to take advantage of me? No, I'm not dissapointed.
bit more wistful

```suggestion
……襲わないのですか？　いえ、がっかりしてませんよ。=...You're not going to take advantage of me? Oh, no, I'm not disappointed.
```

2021-06-16 11:28 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/2/translation.txt
> +誠にありがとうございました。……もしかして、アブノーマルなセックスは好みではなかったのでしょうか？=Thank you for your help. ...Could it be, you're not into abonormal sex?
```suggestion
誠にありがとうございました。……もしかして、アブノーマルなセックスは好みではなかったのでしょうか？=Thank you for your help. ...Maybe you're not into kinky sex?
```

2021-06-16 11:33 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/3/translation.txt
> +好き放題されてしまうのですね……昂ります。=To be unable to resist anything being done to you... It's so exciting.
```suggestion
好き放題されてしまうのですね……昂ります。=I can't stop you from doing whatever you want... I'm getting excited.
```
or
```suggestion
好き放題されてしまうのですね……昂ります。=You can do whatever you want... I'm getting excited.
```

2021-06-16 11:33 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +ここへきて尿意が……私はとうとう天から見放されたようです……=I can feel the urge to pee... It looks like my time has run out...
well, it seems like she is just getting the urge, and realizing she's in dire straights, since she can't get out. so the event has not yet happened. 
and yes, already mentioned it in discord, that mtl was so funny i really wanted to keep it, if you think it works too, i'll definitely go with it :D   (and, ofc, luck was one of the variants i thought as well, but it felt even more remote :P )

2021-06-16 11:35 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/4/translation.txt
> +……見て見ぬふりをされるのが、一番辛いです。=...The hardest thing is to overlook this.
I'm not 100% sure on this, but...
```suggestion
……見て見ぬふりをされるのが、一番辛いです。=...It's hard to be ignored.
```

2021-06-16 11:40 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +……すみません。理由を明かすことはできませんが、一刻も早く助けていただけないでしょうか。お願い致します。=...Excuse me. I can't reveal the reason, but could you please help me as soon as possible? Thank you.
does using quickly after "...excuse me" work? it feels a bit odd to start like that and then suddenly be urgent. maybe move it at the end, "help me quickly"? again, if you say it works at the start, i don't really have anything against it

2021-06-16 11:41 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/18/1/translation.txt
> +……この不格好な姿には、深い事情があるのです。好んでしているわけではありません。=...There's an explanation for this awkward appearence. It's not something I like to do.
Maybe just  `...There's an explanation for this.` or `...I can explain how I got this way`

2021-06-16 11:46 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/18/1/translation.txt
> +気が済むまで犯してからで構いませんので、助けていただけないでしょうか。お願い致します。=You can take me as much as you wish, but can you please help me afterwards?
```suggestion
気が済むまで犯してからで構いませんので、助けていただけないでしょうか。お願い致します。=You can use me until you're satisfied, but can you please help me afterwards?
```

2021-06-16 11:49 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/19/1/translation.txt
> +突然、腰に力が入らなくなり……もし襲うつもりでしたら、そっとしていただけないでしょうか。=I suddenly lost strength in my lower back. If you intend to use me, could you please do it gently?
```suggestion
突然、腰に力が入らなくなり……もし襲うつもりでしたら、そっとしていただけないでしょうか。=I threw my back out... If you intend to use me, please be gentle.
```

2021-06-16 11:50 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +犯しまくる絶好の機会だ、そういったことをお考えなのでしょうね。=I guess you're probably thinking this is a great opportunity to attack me, right?
how about ", i bet." or maybe even "aren't you?". she's actually egging him on, girl is in slavery mode.

2021-06-16 11:52 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/4/translation.txt
> +ここで放置プレイですか……勿論、嫌いではありません。=Is this neglect play? ...Of course, I don't mind it.
```suggestion
ここで放置プレイですか……勿論、嫌いではありません。=Are you going to abandon me here? ...Fine, I don't care.
```

2021-06-16 11:56 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +一番見られたくない方に、見つかるとは……みっともない姿をお見せして申し訳ございません。=I'm deeply sorry to appear as such... In front of the person I least wanted to see me like this.
I chose the wording so it was ambiguous if it was because she dislikes the player, or because she's does like the player and so is embarrassed. But either of your suggestions is fine.

2021-06-16 11:58 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +……間抜けな姿になっていることは充分自覚しておりますので、あまり見ないでいただけると助かります。=...I'm fully aware of how stupid I look, so I would appreciate it if you didn't stare too much.
It's one sentence. In this case `...` is like a `,`:  "I` know I look [pause] stupid"

I think it should be: if it's the same sentence, don't capitalize. If it's a new sentence, then capitalize.  @SpockBauru: oppinion?

2021-06-16 11:59 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +ここへきて尿意が……私はとうとう天から見放されたようです……=I can feel the urge to pee... It looks like my time has run out...
I think the idea of the gods turning away and luck running out are equivalent here

2021-06-16 12:00 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +……すみません。理由を明かすことはできませんが、一刻も早く助けていただけないでしょうか。お願い致します。=...Excuse me. I can't reveal the reason, but could you please help me as soon as possible? Thank you.
No, that's the correct way someone would start when they **need** help from someone they don't want to ask for help from

2021-06-16 12:03 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +犯しまくる絶好の機会だ、そういったことをお考えなのでしょうね。=I guess you're probably thinking this is a great opportunity to attack me, right?
Just leave the `, right?` then I think

2021-06-16 12:17 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/5/translation.txt
> +ただただ不愉快です。これ以上、私に関わらないでもらえますか？=I find it simply unpleasant. Could you please not engage me any further?
This is after you fail to prevent her leaving so `That was unpleasant` seems right as it refers to what just happened. `It was unpleasant` sounds less specific as to what was unpleasant.

2021-06-16 12:18 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/2/translation.txt
> +誠にありがとうございました。……もしかして、アブノーマルなセックスは好みではなかったのでしょうか？=Thank you for your help. ...Could it be, you're not into abonormal sex?
KINKY, that was the term! god, I knew there was a term for this that i couldn't recall for the life of me! :D  thank you :D

2021-06-16 12:20 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/3/translation.txt
> +好き放題されてしまうのですね……昂ります。=To be unable to resist anything being done to you... It's so exciting.
went with the first, feels more in line with her kinkiness :P

2021-06-16 12:28 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/4/translation.txt
> +……見て見ぬふりをされるのが、一番辛いです。=...The hardest thing is to overlook this.
i think she's actually refering to it being hard to get over the fact that he's abandoning her when in need.  (she's at favor affection, so she likely had expectations)

2021-06-16 12:30 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/18/1/translation.txt
> +……この不格好な姿には、深い事情があるのです。好んでしているわけではありません。=...There's an explanation for this awkward appearence. It's not something I like to do.
went with the first, she doesn't really seem to explain :P

2021-06-16 12:33 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/19/1/translation.txt
> +突然、腰に力が入らなくなり……もし襲うつもりでしたら、そっとしていただけないでしょうか。=I suddenly lost strength in my lower back. If you intend to use me, could you please do it gently?
yeah, as expected, english has a lot of awkward phrases for back pains :P

2021-06-16 12:42 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/4/translation.txt
> +ここで放置プレイですか……勿論、嫌いではありません。=Is this neglect play? ...Of course, I don't mind it.
girl is slave, and there apparently is some sort of kinky foreplay/sex involving neglect. it's not like she doesn't care, in fact, she's really interested.
how do you want to proceed?

2021-06-16 12:45 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/16/5/translation.txt
> +ただただ不愉快です。これ以上、私に関わらないでもらえますか？=I find it simply unpleasant. Could you please not engage me any further?
yeah, i was going for the less specific route, but i had the wrong premise, as per your explanation, it's very specific indeed :D

2021-06-16 12:47 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +一番見られたくない方に、見つかるとは……みっともない姿をお見せして申し訳ございません。=I'm deeply sorry to appear as such... In front of the person I least wanted to see me like this.
went with first suggestion then.

2021-06-16 12:47 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/4/translation.txt
> +ここで放置プレイですか……勿論、嫌いではありません。=Is this neglect play? ...Of course, I don't mind it.
`Fine, I don't care.` when he leaves would imply she really does care and is upset he chose to leave her.  `Fine, see if I care` could also work.

2021-06-16 12:49 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +……すみません。理由を明かすことはできませんが、一刻も早く助けていただけないでしょうか。お願い致します。=...Excuse me. I can't reveal the reason, but could you please help me as soon as possible? Thank you.
roger that! done

2021-06-16 12:50 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/1/translation.txt
> +犯しまくる絶好の機会だ、そういったことをお考えなのでしょうね。=I guess you're probably thinking this is a great opportunity to attack me, right?
ok, left it

2021-06-16 13:06 UTC, GenericUser394753 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/4/translation.txt
> +ここで放置プレイですか……勿論、嫌いではありません。=Is this neglect play? ...Of course, I don't mind it.
i don't want to make it seem like i'm inflexible, but i don't exactly think that's the idea behind this line. you can listen to the girl if you open bdata\sound\data\pcm\c00\adv\30.unity3d in sb3u and then go to "hsa_00_015_07_03_00_00". she really doesn't strike me like she's upset :P

2021-06-16 14:56 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/4/translation.txt
> +ここで放置プレイですか……勿論、嫌いではありません。=Is this neglect play? ...Of course, I don't mind it.
Ok, in that case: `Well, I don't mind.` maybe?  `Of course, I don't mind it.` doesn't sound right to me.

2021-06-16 15:03 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/4/translation.txt
> +……見て見ぬふりをされるのが、一番辛いです。=...The hardest thing is to overlook this.
Now I'm not sure what she's saying... could it be: `...it'll be hard to pretend I didn't see you there.` (like she knows he came, saw her, and left, and really wishes he hadn't)

2021-06-16 19:53 UTC, GeBo1 requested changes
Looking good, just a few things.

2021-06-16 19:53 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/15/2/translation.txt
> +ありがとうございました。これ以上お傍にいたら、益々離れがたくなるので、これで失礼致します。=Thank you so much! The longer I stay with you, the harder, the harder it is to part, so I will take my leave now.
Some text got duplicated
```suggestion
ありがとうございました。これ以上お傍にいたら、益々離れがたくなるので、これで失礼致します。=Thank you so much! The longer I stay with you, the harder it is to part, so I will take my leave now.
```

2021-06-16 19:53 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c00/30/17/4/translation.txt
> +……見て見ぬふりをされるのが、一番辛いです。=...The hardest thing is to overlook this.
I think go with `...It will be hard to forgive this.`

2021-06-17 13:32 UTC, GeBo1 approved these changes

2021-06-17 14:05 UTC, merged