Updated translations.
IllusionMods/HS2-Translation pull request #77
Opened 2023-02-02 05:35 UTC by NeonFrights

I'm focusing on updating and expanding on the translations provided by the machine translator. I'll make it a personal project to cover as much as possible during my free time over the next few months.

2023-02-06 14:27 UTC, SpockBauru requested changes
There are some major issues regarding lines that are both uncommented and untranslated. I cannot merge without fixing these issues.
Overall, I like you interpretation of the Sadistic character. She’s dirty, sarcastic, and somewhat aggressive, a true dominatrix. But sometimes you are getting “too far”, I recommend you make a revision and tone down the parts that are too much out of context (there are not many of them).
There are several punctuation and uppercase misses, please consider use the Style Check tool: https://github.com/SpockBauru/TranslationTools_Illusion

2023-02-06 14:27 UTC, SpockBauru commented on Translation/en/RedirectedResources/assets/abdata/list/h/sound/voice/30/hvoice_c07_02_01/translation.txt
> +んんっ、動けない分……オマエの動きがもろに分かるな……（オマエのがどんどん口の中で大きく）=
More uncommented and untranslated lines...

2023-02-07 06:49 UTC, NeonFrights commented
> There are some major issues regarding lines that are both uncommented and untranslated. I cannot merge without fixing these issues. Overall, I like you interpretation of the Sadistic character. She’s dirty, sarcastic, and somewhat aggressive, a true dominatrix. But sometimes you are getting “too far”, I recommend you make a revision and tone down the parts that are too much out of context (there are not many of them). There are several punctuation and uppercase misses, please consider use the Style Check tool: https://github.com/SpockBauru/TranslationTools_Illusion
> 
> Tip: GitHub is hiding many conversations, click in "Load more" when you find bellow.

Thank you for your response! I will look over the suggested changes, especially regarding the use of trademarked material, as I continue the translation efforts. I am also making an effort to add as much definable personality as possible rather than have the girl simply serve as an object, for this reason I am adding conversational cues that don't necessarily relate to the core objective of getting with her. I have also had issues with context as the (machine) translations do not denote the specific scenes involved and I only recognise the translations are misplaced when they display in-game in the unintended scene(s). As for punctuation, I have missed some parentheses to indicate she is communicating through her thoughts, but uppercase following an ellipsis in standard English is only appropriate when it indicates the beginning of a new sentence - if what follows the ellipsis is a continuation of the same sentence, it must be lowercase! Thank you again for your feedback, I look forward to you reviewing the completed project... however, I don't know yet if I will attempt any of the other personalities.

2023-02-07 14:49 UTC, NeonFrights commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/30/00/2/translation.txt
> +顔を真っ赤にしてお誘いか？　断ったら泣いちまいそうだな。=Sure! I'll let you put it in me if you want, but you have to let me sit on your face in return.
Thank you! I don't know any Japanese and Google Translate doesn't help much, the original text seems very informal and full of slang that Translate doesn't recognise in context, which would be expected.

2023-02-07 15:02 UTC, NeonFrights commented
Hi again! Just to enquire, do you have a list of the scenarios occurring for each number within /c07/30, /34, and /50, along with the h scenes for /hvoice_c07... ? It would certainly make things a lot easier!

2023-02-07 23:19 UTC, SpockBauru commented
> Hi again! Just to enquire, do you have a list of the scenarios occurring for each number within /c07/30, /34, and /50, along with the h scenes for /hvoice_c07... ? It would certainly make things a lot easier!

I wish I have something like this... If you manage to make it, please share! It will help a lot!

2023-02-08 04:00 UTC, NeonFrights commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/30/31/10/translation.txt
> +まさかトイレでヤることになるとはな。オレまで変態の仲間入りだ……=Fucking him in the toilet, and liking it... so this is how I learn how much of a pervert I am...
It certainly should! Will have those little details fixed for the next commit submission!

2023-05-01 14:17 UTC, merged